### ISSUE TITLE
Sendpass tokens are not deleted after use

### ISSUE THREAD

**Issue by cryogen** [oftc/oftc-ircservices#1]
They probably should be, or else the password can be reset multiple times and if someone pastes their token after use the account can be taken over

**Comment by namoscagnm** [comment]
It actually happened to me! See https://github.com/oftc/oftc-ircservices/issues/23

**Comment by Gryllida** [comment]
If I am not mistaken, changing the master nick eliminates the risk - it makes it impossible to use the key for the account, it is no longer valid. This is perhaps a workaround.

**Comment by ChristophBerg** [comment]
<@Myon> shouldn't even be hard, add a DB call at modules/nickserv.c line 1815

**Comment by dwfreed** [comment]
From #31:

> In order to fix the underlying issue, the sendpass token either would need to be something random, stored in and retrieved from the database, or derived from the password hash, so that it's automatically invalidated when the user's password changes.
