### ISSUE TITLE
Resurrect reloading of ruby modules

### ISSUE THREAD

**Issue by ChristophBerg** [oftc/oftc-ircservices#15]
d56402c371ff24143abf98cf48d11e274e04f074 fixes loading of ruby modules, but unfortunately rb_require doesn't reload the file from disk when called again. The web says to use "load" instead, but my attempts to do that from C failed, so I went with the require version. We should fix that eventually, though.

**Comment by dwfreed** [comment]
Fixed by 3fa04c5
